### PR TITLE
Use HTTPS where we can; remove hard-coded port 80

### PR DESCRIPTION
**Pull request by stephendonner**
I confess I haven't fully tested this, yet, plus there's potentially work to be done in https://github.com/pytest-dev/pytest-selenium/blob/b78f993a68abf63964e61256f420779133e70391/pytest_selenium/drivers/testingbot.py#L32

### CODE REVIEW

**Comment by davehunt** [comment]
Can you clarify what you mean by work to be done? Is there a reason you haven't tested this? I'd prefer not to merge unless we have confidence that we're not breaking things for users of these cloud providers.

**Comment by stephendonner** [comment]
Besides testing browserstack, crossbrowsertesting, and testingbot (which I will do once I've got my just-now broken Python environment (due to X-code install) fixed, I wanted to check with you on whether we can/should change anything with the testingbot driver, particularly, due to the way it seemingly uses passed-in variables for [key, secret, host, port].

And, apologies - I didn't mean for this to be ready for review just yet, nor that you nor other folks should pick up my slack.  I'll carry it home, either by figuring it out or pinging you for help, when you're free, and my environment is back!

**Comment by davehunt** [comment]
After reading your comment, I read mine again, and think it was misleading in tone. I didn't mean it to sound aggressive. Fortunately, you know me, and hopefully realised this was not my intent. I'll add a label to indicate this is still a work in progress.

The host/port settings for TestingBot are to support a local [TestingBot Tunnel](https://testingbot.com/support/other/tunnel), and according to the documentation this supports https, so we should be okay to change the scheme. Of course, we should test this before we release the changes.

**Comment by davehunt** [comment]
* `test_chrome.py` failed because `chromedriver` is not in your path
* `test_edge.py` failed because `MicrosoftWebDriver.exe` is not in your path
* `test_phantomjs.py` failed because `phantomjs` is not in your path
* `test_safari.py` failed because 'Allow Remote Automation' is not enabled in Safari
* `test_saucelabs.py` failed because your token appears to be different, perhaps @BeyondEvil can help with that one?
* `test_testingbot.py` failed because of `URLError: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:726)>`. I suspect this is from your changes?

> I understand this is a module/package, so probably just running `tox` here isn't the right way, is it?

I'm not sure I understand the question. The [documentation](http://pytest-selenium.readthedocs.io/en/latest/development.html#running-tests) covers running the tests, and they mostly worked. We could add a note about requiring the various driver executables, though.

>  I'm not sure if I need to add credentials to and use all three .testingbot, .crossbrowsertesting, and .browserstack config files?

No, the tests do not cover the cloud providers beyond some basic checks. You will need to test these manually, and you can use these configuration files to store the credentials if you like. I'd advise against storing them in the project directory though.

**Comment by BeyondEvil** [comment]
Honestly @stephendonner and @davehunt I'm not sure what is going on with the token tests on Stephens machine. I pulled his changes (this PR) and the token tests pass. They also passed on the Travis CI run (others failed). https://travis-ci.org/pytest-dev/pytest-selenium/jobs/385716120#L590

Not sure if there's something in the implementation of hmac or md5 that is somehow platform-dependent.

**Comment by BeyondEvil** [comment]
Interesting, @davehunt, I'm on macOS 10.12.6 🤔

**Comment by BeyondEvil** [comment]
Could either of you try adding more info to the datetime object?

`monkeytime = datetime.datetime(2020, 12, 25, 17, 10, 10, 10, tzinfo=None)`

See if that fixes it?

**Comment by stephendonner** [comment]
Done, @BeyondEvil!

**Comment by BeyondEvil** [comment]
Did that fix the failures you were seeing @stephendonner ?

**Comment by stephendonner** [comment]
@BeyondEvil nope:

```
testing/test_saucelabs.py::test_auth_token[token-5d5b3d4fe1fcb72edf5f8c431eb10175] FAILED [ 88%]
testing/test_saucelabs.py::test_auth_token[day-e9480f85e8183e94e39fc69af685831c] FAILED [ 89%]
testing/test_saucelabs.py::test_auth_token[hour-441bac7116b1eeb026fed2a0942aad57] FAILED [ 91%]
...
___________ test_auth_token[token-5d5b3d4fe1fcb72edf5f8c431eb10175] ____________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x104342e50>
auth_type = 'token', auth_token = '5d5b3d4fe1fcb72edf5f8c431eb10175'

    @pytest.mark.parametrize(('auth_type', 'auth_token'),
                             [('none', ''),
                              ('token', '5d5b3d4fe1fcb72edf5f8c431eb10175'),
                              ('day', 'e9480f85e8183e94e39fc69af685831c'),
                              ('hour', '441bac7116b1eeb026fed2a0942aad57')])
    def test_auth_token(monkeypatch, auth_type, auth_token):
        import datetime
        from pytest_selenium.drivers.saucelabs import SauceLabs, get_job_url
    
        monkeypatch.setattr(datetime, 'datetime', MonkeyDatetime)
        monkeypatch.setenv('SAUCELABS_USERNAME', 'foo')
        monkeypatch.setenv('SAUCELABS_API_KEY', 'bar')
    
        session_id = '12345678'
        url = 'https://saucelabs.com/jobs/{}'.format(session_id)
    
        if auth_type != 'none':
            url += '?auth={}'.format(auth_token)
    
        result = get_job_url(Config(auth_type), SauceLabs(), session_id)
>       assert result == url
E       AssertionError: assert 'https://sauc...fd8599111ce42' == 'https://sauce...f8c431eb10175'
E         - https://saucelabs.com/jobs/12345678?auth=3546479d7ef78c6931afd8599111ce42
E         + https://saucelabs.com/jobs/12345678?auth=5d5b3d4fe1fcb72edf5f8c431eb10175

/Users/stephendonner/pytest-selenium/testing/test_saucelabs.py:100: AssertionError
____________ test_auth_token[day-e9480f85e8183e94e39fc69af685831c] _____________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x103f43f10>
auth_type = 'day', auth_token = 'e9480f85e8183e94e39fc69af685831c'

    @pytest.mark.parametrize(('auth_type', 'auth_token'),
                             [('none', ''),
                              ('token', '5d5b3d4fe1fcb72edf5f8c431eb10175'),
                              ('day', 'e9480f85e8183e94e39fc69af685831c'),
                              ('hour', '441bac7116b1eeb026fed2a0942aad57')])
    def test_auth_token(monkeypatch, auth_type, auth_token):
        import datetime
        from pytest_selenium.drivers.saucelabs import SauceLabs, get_job_url
    
        monkeypatch.setattr(datetime, 'datetime', MonkeyDatetime)
        monkeypatch.setenv('SAUCELABS_USERNAME', 'foo')
        monkeypatch.setenv('SAUCELABS_API_KEY', 'bar')
    
        session_id = '12345678'
        url = 'https://saucelabs.com/jobs/{}'.format(session_id)
    
        if auth_type != 'none':
            url += '?auth={}'.format(auth_token)
    
        result = get_job_url(Config(auth_type), SauceLabs(), session_id)
>       assert result == url
E       AssertionError: assert 'https://sauc...caeea66d29ed1' == 'https://sauce...fc69af685831c'
E         - https://saucelabs.com/jobs/12345678?auth=7f796910ade515b7c97caeea66d29ed1
E         + https://saucelabs.com/jobs/12345678?auth=e9480f85e8183e94e39fc69af685831c

/Users/stephendonner/pytest-selenium/testing/test_saucelabs.py:100: AssertionError
____________ test_auth_token[hour-441bac7116b1eeb026fed2a0942aad57] ____________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x102dc1950>
auth_type = 'hour', auth_token = '441bac7116b1eeb026fed2a0942aad57'

    @pytest.mark.parametrize(('auth_type', 'auth_token'),
                             [('none', ''),
                              ('token', '5d5b3d4fe1fcb72edf5f8c431eb10175'),
                              ('day', 'e9480f85e8183e94e39fc69af685831c'),
                              ('hour', '441bac7116b1eeb026fed2a0942aad57')])
    def test_auth_token(monkeypatch, auth_type, auth_token):
        import datetime
        from pytest_selenium.drivers.saucelabs import SauceLabs, get_job_url
    
        monkeypatch.setattr(datetime, 'datetime', MonkeyDatetime)
        monkeypatch.setenv('SAUCELABS_USERNAME', 'foo')
        monkeypatch.setenv('SAUCELABS_API_KEY', 'bar')
    
        session_id = '12345678'
        url = 'https://saucelabs.com/jobs/{}'.format(session_id)
    
        if auth_type != 'none':
            url += '?auth={}'.format(auth_token)
    
        result = get_job_url(Config(auth_type), SauceLabs(), session_id)
>       assert result == url
E       AssertionError: assert 'https://sauc...f7c95be354afd' == 'https://sauce...ed2a0942aad57'
E         - https://saucelabs.com/jobs/12345678?auth=fe51fb4767b36bba653f7c95be354afd
E         + https://saucelabs.com/jobs/12345678?auth=441bac7116b1eeb026fed2a0942aad57

/Users/stephendonner/pytest-selenium/testing/test_saucelabs.py:100: AssertionError
```

**Comment by BeyondEvil** [comment]
@stephendonner Bummer. Ah, well. I'll do a separate PR with the changed test tomorrow. If @davehunt approves, we can merge that and then you can pull it as well. 👍

**Comment by stephendonner** [comment]
@BeyondEvil sounds good, thanks!
@davehunt I haven't purposely been dragging my feet on this, but if it can wait until the All-Hands, I'd like to use it as an opportunity to learn, with you - cheers!

**Comment by davehunt** [comment]
> I haven't purposely been dragging my feet on this, but if it can wait until the All-Hands, I'd like to use it as an opportunity to learn, with you - cheers!

No worries, it's not a priority.

**Comment by davehunt** [comment]
@stephendonner can you remind me of the status of this? I've just merged #168 so perhaps try pulling and rebasing to see if your tests are passing.

**Comment by BeyondEvil** [comment]
I'm closing this in favor of #178

**Pull request closed without merging**
