### PR TITLE
Ensure compatibility with next `pytest-xdist` release

### LINKED ISSUE #238: Upcoming incompatibility in pytest-xdist 2.0: "slave" aliases removed
Hi!

As per https://github.com/pytest-dev/pytest-xdist/pull/541, pytest-xdist 2.0 will remove the deprecated "slave" 
aliases, which have been replaced by "worker" since pytest-xdist 1.22.

To avoid breakage, the team suggests to update your package to use the new terms, and make a new release to avoid sudden breakages once pytest-xdist 2.0 is released.

cc @Zac-HD @RonnyPfannschmidt

Thanks!

### PR DESCRIPTION
**Pull request by Zac-HD**
Fixes #238.

### CODE REVIEW

**Comment by Zac-HD** [comment]
@Dude-X - I don't *think* the CI failure is because of these changes?

**Comment by BeyondEvil** [comment]
> @Dude-X - I don't _think_ the CI failure is because of these changes?

No they're not. They're due to a bug introduced in pytest-html v2.1.0.

**Comment by BeyondEvil** [comment]
As soon as #243 is merged, you can rebase this and tests should pass.

**Comment by BeyondEvil** [comment]
Please rebase and tests should pass @Zac-HD Thanks!

**Comment by Zac-HD** [comment]
@BeyondEvil and indeed they do!  Ready to merge and release then?

**Comment by BeyondEvil** [comment]
> @BeyondEvil and indeed they do! Ready to merge and release then?

Yes! Will start on a release right away.

**Comment by BeyondEvil** [comment]
https://github.com/pytest-dev/pytest-selenium/pull/244

**Pull request merged**
