### PR TITLE
Use HTTPS where we can, and remove hard-coded port 80

### PR DESCRIPTION
**Pull request by stephendonner**
Sorry for the delay, and the mess.  I've taken another clean shot (hopefully) at this.

### CODE REVIEW

**Comment by BeyondEvil** [comment]
Do all of the providers support HTTPS? Have you tested this? I can test against Testingbot if need be, because I have an account there. @stephendonner

**Comment by stephendonner** [comment]
@BeyondEvil thanks; I could clearly use the help, here.  Yes, TestingBot's API supports HTTPS, and is used in their API docs' examples: https://testingbot.com/support/api

The Python client, though, uses primarily HTTP throughout its docs.

**Comment by BeyondEvil** [comment]
This should now be handled by #190 #191 and #192

**Comment by BeyondEvil** [comment]
As my previous comment stated, this has now been handled.
You can go head an close this PR if there's nothing else you want to add @stephendonner

Thanks for bringing this to us.   👍

**Pull request closed without merging**
