### PR TITLE
Full in pyproject.toml and Poetry

### PR DESCRIPTION
**Pull request by BeyondEvil**

### CODE REVIEW

**Comment by BeyondEvil** [comment]
Hey @isaulv 

Trying to get back into this.

Would be nice with a second pair of eyes on this. Not sure what the Windows failures are about.

**Review by isaulv — APPROVED** [review]
LGTM

**Comment by isaulv** [comment]
@BeyondEvil I think the Windows tests are failing due to the driver dying somewhere. Those url lib failures look like the driver has stopped responding or crashed.

**Comment by BeyondEvil** [comment]
> @BeyondEvil I think the Windows tests are failing due to the driver dying somewhere. Those url lib failures look like the driver has stopped responding or crashed.

It's always the same tests.

Also, any idea why the testingbot test fails?

**Pull request merged**
