### PR TITLE
Fix issue with using localhost for TestingBot tunnel

### PR DESCRIPTION
**Pull request by BeyondEvil**
Fixes: #216

### CODE REVIEW

**Comment by Dude-X** [comment]
Is it possible that the port is 443 the standard HTTPS port and no longer custom? I would prefer to try to maintain encryption.

**Comment by BeyondEvil** [comment]
> Is it possible that the port is 443 the standard HTTPS port and no longer custom? I would prefer to try to maintain encryption.

When using TestingBot without a tunnel we use HTTPS and port 443. But what the tunnel does is it enables you to let the TestingBot VM access any webserver running locally on your machine (and not exposed to the public internet).

The [tunnel](https://testingbot.com/support/other/tunnel) itself is secure and uses SSH to communicate with the TestingBot VM. But for the tests to be able to communicate with the VM (via the tunnel) you have to point the tests to `localhost` and port `4445` (default, configurable).

So the "unsecured" http-traffic is happening only on your local machine, never with the TB VM.

Testing bot [example](https://testingbot.com/support/other/tunnel/examples.html)

Our [docs](https://pytest-selenium.readthedocs.io/en/latest/user_guide.html#local-tunnel)

Let me know if that clears things up @Dude-X

**Comment by Dude-X** [comment]
Thanks for the clarification.

**Comment by BeyondEvil** [comment]
Sorry, had to add the changes to `news.rst` because I want to release a new version asap, to fix this bug. @Dude-X

**Pull request merged**
