### PR TITLE
Removed xdist check since processes need to be able to set the sensitive URL

### LINKED ISSUE #252: Issue in pytest-selenium 2.0.0 when using with pytest-xdist
I'm using pytest-xdist with pytest- selenium 2.0.0 plugin to run tests in parallel.
Note: Same setup is working fine with pytest-selenium 1.17.0

I'm using following command to run tests.
`pytest --driver Chrome --base-url 'https://example.com' -n 2`

Error:
```
[gw1] darwin -- Python 3.8.3 /Users/admin/workspace/smoke-tests/venv/bin/python3.8

request = <SubRequest 'sensitive_url' for <Function test_should_verify_welcome_page>>, base_url = 'https://example.com'

    @pytest.fixture(scope="session")
    def sensitive_url(request, base_url):
        """Return the first sensitive URL from response history of the base URL"""
        if not base_url:
            return False
        # consider this environment sensitive if the base url or any redirection
        # history matches the regular expression
        urls = [base_url]

        # lazy import requests for projects that don't need requests
        import requests

        try:
            response = requests.get(base_url, timeout=10)
            urls.append(response.url)
            urls.extend([history.url for history in response.history])
        except requests.exceptions.RequestException:
            pass  # ignore exceptions if this URL is unreachable
        search = partial(re.search, request.config.getoption("sensitive_url"))
>       matches = list(map(search, urls))
```

### PR DESCRIPTION
**Pull request by Dude-X**
Fixes #252

### CODE REVIEW

**Comment by BeyondEvil** [comment]
Doesn't `pytest_configure` happen before spawning off child-processes anyway? 🤔

**Comment by Dude-X** [comment]
@BeyondEvil yes, but I wonder if xdist sends all the child worker processes a fully initialized config object, or it's still the responsibility of the worker process to configure themselves.

**Comment by BeyondEvil** [comment]
> @BeyondEvil yes, but I wonder if xdist sends all the child worker processes a fully initialized config object, or it's still the responsibility of the worker process to configure themselves.

Any input here @Zac-HD ? 😊

**Comment by Zac-HD** [comment]
I don't know, sorry, not actually an xdist expert.

**Comment by BeyondEvil** [comment]
Sorry for being slow on this. Can we write a test for this change?

**Comment by Dude-X** [comment]
@BeyondEvil sure with the `pytester` plugin you can write a test for this.

**Comment by BeyondEvil** [comment]
Great! 👍

**Review by BeyondEvil — CHANGES_REQUESTED** [review]
Add a test and we're good to go! 👍

**Review by BeyondEvil — APPROVED** [review]

**Pull request merged**
